namespace WreckSector.Model.Gameplay
{
    /// <summary>
    /// The unique tiles that can appear in the deck.  Each tile type will have its own unique associated graphic.
    /// Bombs are not a TileType, and are special.
    /// </summary>
    public enum TileType
    {
        AllyF,
        AllyE,
        AllyD,
        AllyC,
        AllyB,
        AllyA,
        AllyS,
        AllySPlus,
        AllySPrime,
        Attack,
        Blessing,
        Choice,
        Credits1,
        Credits3,
        Credits5,
        Credits10,
        Credits15,
        Credits20,
        Credits30,
        Credits50,
        Credits100,
        Credits150,
        Credits255,
        Curse,
        Doom,
        EnemyF,
        EnemyE,
        EnemyD,
        EnemyC,
        EnemyB,
        EnemyA,
        EnemyS,
        EnemySPlus,
        EnemySPrime,
        Fortune,
        HullBreach,
        Kidnap,
        LifeSupport,
        LifeSupportContainers,
        MedKit1,
        MedKit2,
        MedKit4,
        Poison,
        PowerCell1,
        PowerCell2,
        PowerCell4,
        Prison,
        Promotion,
        Raid,
        RepairShop,
        Saboteur,
        Scrap1,
        Scrap2,
        Scrap4,
        TileShop,
        Treasure,
        Turret,
        Vault,
    }
}
